# Generated by Django 4.1.7 on 2023-03-26 22:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('effect', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('foods', models.ManyToManyField(related_name='trigger_foods', to='sapdb.food')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='triggers',
            field=models.ManyToManyField(related_name='food_triggers', to='sapdb.trigger'),
        ),
    ]
