# Generated by Django 4.1.7 on 2023-03-26 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='tier',
            field=models.IntegerField(choices=[(1, 'Tier 1'), (2, 'Tier 2'), (3, 'Tier 3'), (4, 'Tier 4'), (5, 'Tier 5'), (6, 'Tier 6')], default=0),
        ),
    ]
