# Generated by Django 4.1.7 on 2023-03-26 23:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sapdb', '0003_remove_food_id_remove_trigger_id_alter_food_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('release', models.DateField()),
                ('animals', models.ManyToManyField(related_name='pack_foods', to='sapdb.food')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='packs',
            field=models.ManyToManyField(related_name='food_packs', to='sapdb.pack'),
        ),
    ]
