# Generated by Django 4.1.7 on 2023-03-26 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sapdb', '0004_pack_food_packs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pack',
            old_name='animals',
            new_name='foods',
        ),
    ]
