# Generated by Django 4.1.7 on 2023-03-26 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sapdb', '0005_rename_animals_pack_foods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pack',
            name='release',
        ),
    ]
