# Generated by Django 4.1.7 on 2023-03-26 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapdb', '0006_remove_pack_release'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pack',
            name='id',
        ),
        migrations.AlterField(
            model_name='pack',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
