# Generated by Django 4.1.7 on 2023-03-26 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapdb', '0007_remove_pack_id_alter_pack_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='image',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
