# Generated by Django 4.1.7 on 2023-04-29 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapdb', '0008_pack_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Use',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('foods', models.ManyToManyField(related_name='use_foods', to='sapdb.food')),
            ],
        ),
        migrations.DeleteModel(
            name='Trigger',
        ),
        migrations.AlterField(
            model_name='food',
            name='triggers',
            field=models.ManyToManyField(related_name='food_uses', to='sapdb.use'),
        ),
    ]
